//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Gadgeteer.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Gadgeteer.Designer.Resources.PackageUI", typeof(PackageUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any valid connections. Try removing some modules..
        /// </summary>
        internal static string AutoConnectFailed {
            get {
                return ResourceManager.GetString("AutoConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gadgeteer Designer was not able to connect the optional sockets..
        /// </summary>
        internal static string AutoConnectRequiredSockets {
            get {
                return ResourceManager.GetString("AutoConnectRequiredSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately this hardware&apos;s driver is corrupted and cannot be used. Contact its manufacturer.
        ///
        ///{0}.
        /// </summary>
        internal static string DefinitionError {
            get {
                return ResourceManager.GetString("DefinitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no manufacturer).
        /// </summary>
        internal static string DefinitionNoManufacturer {
            get {
                return ResourceManager.GetString("DefinitionNoManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no name).
        /// </summary>
        internal static string DefinitionNoName {
            get {
                return ResourceManager.GetString("DefinitionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .NET Gadgeteer.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgeteer Mainboards.
        /// </summary>
        internal static string MainboardsTabName {
            get {
                return ResourceManager.GetString("MainboardsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} installer was not correctly set up, it does not provide a compatible assembly for .NET Micro Framework version {1}..
        /// </summary>
        internal static string MissingAssembly {
            get {
                return ResourceManager.GetString("MissingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hardware is currently not usable, as it requires .NET Gadgeteer Core version {0} or newer to be installed, and version {1} is currently installed.
        ///Check http://gadgeteer.codeplex.com/ for the latest version..
        /// </summary>
        internal static string WarningGVersion {
            get {
                return ResourceManager.GetString("WarningGVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hardware is currently not usable, as it requires one of the following .NET Micro Framework versions: {0}.
        ///However, this project uses .NET Micro Framework {1}..
        /// </summary>
        internal static string WarningMFVersion {
            get {
                return ResourceManager.GetString("WarningMFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a reference to the .NET Gadgeteer Core version {0} or newer in order to use this hardware..
        /// </summary>
        internal static string WarningNoG {
            get {
                return ResourceManager.GetString("WarningNoG", resourceCulture);
            }
        }
    }
}
