//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Microsoft.Gadgeteer.Designer
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Socket
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateSocketMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.SocketUse == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Microsoft.Gadgeteer.Designer.GadgeteerDSLDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Socket", this.Label, "SocketUse"),
						"DSL0001", this);
			}
		} // ValidateSocketMultiplicity
	} // class Socket
} // Microsoft.Gadgeteer.Designer

namespace Microsoft.Gadgeteer.Designer
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class SocketUse
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateSocketUseMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Socket == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Microsoft.Gadgeteer.Designer.GadgeteerDSLDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"SocketUse", this.Label, "Socket"),
						"DSL0001", this);
			}
		} // ValidateSocketUseMultiplicity
	} // class SocketUse
} // Microsoft.Gadgeteer.Designer

	
 