// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the Apache v.2 license.
namespace Gadgeteer.Interfaces
{
    using System;
    using Microsoft.SPOT;
    using Microsoft.SPOT.Hardware;
    using Gadgeteer.Modules;

    /// <summary>
    /// Represents pulse width modulation (PWM) output using a single socket pin.
    /// </summary>
    public class PWMOutput
    {
        private Cpu.PWMChannel pwmChannel = Cpu.PWMChannel.PWM_NONE;
        private PWM pwm = null;
        private Socket.Pin pin;
        private bool invert = false;
        private bool started = false;

        // Note: A constructor summary is auto-generated by the doc builder.
        /// <summary>
        /// </summary>
        /// <remarks>This automatically checks that the socket supports Type P, and reserves the pin.
        /// An exception will be thrown if there is a problem with these checks.</remarks>
        /// <param name="socket">The socket that supports pulse width modulation (PWM) output.</param>
        /// <param name="pin">The pin on the socket that supports PWM.</param>
        /// <param name="invert">Whether to invert the output voltage.</param>
        /// <param name="module">The module using this PWM output interface, which can be null if unspecified.</param>
        public PWMOutput(Socket socket, Socket.Pin pin, bool invert, Module module)
        {
            this.pin = pin;
            this.invert = invert;
            socket.EnsureTypeIsSupported('P',module);

            switch(pin) 
            {
                case Socket.Pin.Seven: 
                    pwmChannel = socket.PWM7;
                    break;
                case Socket.Pin.Eight:
                    pwmChannel = socket.PWM8;
                    break;
                case Socket.Pin.Nine:
                    pwmChannel = socket.PWM9;
                    break;
                default:
                    if (module != null)
                    {
                        throw new Socket.InvalidSocketException("Module " + module + " cannot use PWM interface on pin " + pin + " - pin must be in range 7 to 9.");
                    }
                    else
                    {
                        throw new Socket.InvalidSocketException("Cannot use PWM interface on pin " + pin + " - pin must be in range 7 to 9.");
                    }
            }

            if (pwmChannel == Cpu.PWMChannel.PWM_NONE)
            {
                // this is a mainboard error that should not happen (we already check for it in SocketInterfaces.RegisterSocket) but just in case...
                throw new Socket.InvalidSocketException("Socket " + socket + " has an error with its PWM functionality. Please try a different socket.");
            }

            socket.ReservePin(pin, module);
        }

        /// <summary>
        /// Sets the frequency and duty cycle of the <see cref="PWMOutput"/> interface and starts the PWM signal.
        /// </summary>
        /// <param name="frequency">Required frequency in Hertz.</param>
        /// <param name="dutyCycle">Duty cycle from 0-1.</param>
        public void Set(int frequency, double dutyCycle)
        {
            if (frequency < 0) throw new ArgumentException("frequency");
            if (dutyCycle < 0 || dutyCycle > 1) throw new ArgumentException("dutyCycle");
            if (pwm == null)
            {
                pwm = new PWM(pwmChannel, frequency, dutyCycle, invert);
                pwm.Start();
                started = true;
            }
            else
            {
                if (started) pwm.Stop();
                pwm.Frequency = frequency;
                pwm.DutyCycle = dutyCycle;
                pwm.Start();
                started = true;
            }
        }

        /// <summary>
        /// Sets the period and high time of the <see cref="PWMOutput"/> interface and starts the PWM signal.
        /// </summary>
        /// <param name="period_ns">Period of the signal in nanoseconds.</param>
        /// <param name="highTime_ns">High time of the signal in nanoseconds.</param>
        public void SetPulse(uint period_ns, uint highTime_ns)
        {
            if(pwm == null) 
            {
                pwm = new PWM(pwmChannel,period_ns, highTime_ns, PWM.ScaleFactor.Nanoseconds, invert);
                pwm.Start();
                started = true;
            }
            else
            {
                if(started) pwm.Stop();
                pwm.Scale = PWM.ScaleFactor.Nanoseconds;
                pwm.Period = period_ns;
                pwm.Duration = highTime_ns;
                pwm.Start();
                started = true;
            }
        }

        /// <summary>
        /// Gets or sets a Boolean value that indicates whether the PWM interface is active, <b>true</b> if active
        /// otherwise <b>false</b>.
        /// </summary>
        public bool Active
        {
            get
            {
                return pwm != null;
            }
            set
            {
                if (Active == value) return;
                if (value)
                {
                    pwm = new PWM(pwmChannel, 1, 0.5, invert);
                    started = false;
                }
                else 
                {
                    if (started) pwm.Stop();
                    pwm.Dispose();
                    pwm = null;
                }
            }
        }
    }

}
