//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Gadgeteer.Designer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeGenerationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeGenerationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Gadgeteer.Designer.CodeGenerationResource", typeof(CodeGenerationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] CustomToolTemplateFile {
            get {
                object obj = ResourceManager.GetObject("CustomToolTemplateFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CustomToolTemplateFileVB {
            get {
                object obj = ResourceManager.GetObject("CustomToolTemplateFileVB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///	&lt;xsl:output method=&quot;html&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///	&lt;xsl:param name=&quot;moreInfoUrl&quot;/&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;head&gt;
        ///			&lt;title&gt;
        ///				&lt;xsl:value-of select=&quot;doc/assembly/name&quot;/&gt;
        ///			&lt;/title&gt;
        ///			&lt;style&gt;
        ///				div, h1, h2, .pageTitle, table, dl, h3, p {font-family: &quot;Segoe UI&quot;, Verdana, Arial; margin: 0px 12px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmldoc2html {
            get {
                return ResourceManager.GetString("xmldoc2html", resourceCulture);
            }
        }
    }
}
