//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Gadgeteer.Designer
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "gadgeteer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Gadgeteer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GadgeteerDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GadgeteerDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GadgeteerDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GadgeteerDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGadgeteerDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GadgeteerDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string GadgeteerDSLPackageId = "e627fec7-215a-4eed-a85e-440df3eb5f5f";
		
		// Editor factory identifier
		public const string GadgeteerDSLEditorFactoryId = "b306cb57-56a9-4c9c-bc13-c489ee1c1d34";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GadgeteerDSLModelExplorerToolWindowId = "8c66aea6-d9d2-414a-9dc4-8ce2f99c952c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Microsoft.Gadgeteer.Designer
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GadgeteerDSLCommandSetId = "b0a166c4-1faa-41a8-85cc-fd791f1bde65";
	}
}