// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific target
// and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Error List, point to "Suppress Message(s)", and click "In Project
// Suppression File". You do not need to add suppressions to this
// file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "gadgeteer", Scope = "resource", Target = "Microsoft.Gadgeteer.Designer.GeneratedCode.DomainModelResx.resources", Justification = "Designer file extension")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLDiagramSerializerBase.#CreateInstance(Microsoft.VisualStudio.Modeling.SerializationContext,System.Xml.XmlReader,Microsoft.VisualStudio.Modeling.Partition)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLDomainModel.#CreateElement(Microsoft.VisualStudio.Modeling.Partition,System.Type,Microsoft.VisualStudio.Modeling.PropertyAssignment[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#InitializeSerialization(Microsoft.VisualStudio.Modeling.Store)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#InternalSaveDiagram(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.Gadgeteer.Designer.GadgeteerDSLDiagram,System.String,System.Text.Encoding,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#InternalSaveModel(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.Gadgeteer.Designer.GadgeteerModel,System.String,System.Text.Encoding,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#LoadModel(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.VisualStudio.Modeling.Partition,System.String,Microsoft.VisualStudio.Modeling.ISchemaResolver,Microsoft.VisualStudio.Modeling.Validation.ValidationController,Microsoft.VisualStudio.Modeling.ISerializerLocator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#LoadModelAndDiagram(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.VisualStudio.Modeling.Partition,System.String,Microsoft.VisualStudio.Modeling.Partition,System.String,Microsoft.VisualStudio.Modeling.ISchemaResolver,Microsoft.VisualStudio.Modeling.Validation.ValidationController,Microsoft.VisualStudio.Modeling.ISerializerLocator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#SaveDiagram(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.Gadgeteer.Designer.GadgeteerDSLDiagram,System.String,System.Text.Encoding,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#SaveModel(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.Gadgeteer.Designer.GadgeteerModel,System.String,System.Text.Encoding,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#SaveModelAndDiagram(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.Gadgeteer.Designer.GadgeteerModel,System.String,Microsoft.Gadgeteer.Designer.GadgeteerDSLDiagram,System.String,System.Text.Encoding,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Microsoft.Gadgeteer.Designer.GadgeteerDSLSerializationHelperBase.#LoadModelAndDiagram(Microsoft.VisualStudio.Modeling.SerializationResult,Microsoft.VisualStudio.Modeling.Store,System.String,System.String,Microsoft.VisualStudio.Modeling.ISchemaResolver,Microsoft.VisualStudio.Modeling.Validation.ValidationController,Microsoft.VisualStudio.Modeling.ISerializerLocator)")]
